---
title: "Task 1"
author: "Roupen Khanjian, Genevieve Chiong, Katelin Seeto"
date: "2/1/2021"
output:
   html_document:
     theme: darkly
     code_folding: hide
     toc: true
     toc_float: true
     number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(janitor)
library(tsibble)
library(feasts)
library(lubridate)
```

```{r}
# Read in the data
fish <- read_csv(here("data", "willamette_fish_passage.csv"))
```

```{r}
# Wrangle the data
fish_ts <- fish %>% 
  clean_names() %>% 
  mutate(date = lubridate::myd(date)) %>% # Convert to date 
  select(date, coho, jack_coho, steelhead) %>% # Select only for date and fish of interest
  replace_na(list(coho = 0, jack_coho = 0, steelhead = 0)) %>%
  pivot_longer(c(coho:steelhead),
               names_to = "species", 
               values_to = "count") %>% # Replace NA values with 0 
  as_tsibble(key = species, index = date) # Convert to tsibble 
```


# Overview {.tabset}

## Original time series 

## Seasonplots

## Annual counts by species 






